apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Sysco-Sample-API-Repo2
  description: >
    The Sysco-Sample-API-Repo is designed to provide sample API
    specifications aligned with the Sysco API guidelines.
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: pep8speaks-org/pep8speaks
    datadoghq.com/dashboard-url: https://p.us5.datadoghq.com/…
    scorecard/jsonDataUrl: "https://mocki.io/v1/d4867d8b-b5d5-4a48-a4ab-79131b5809b8"
spec:
  type: service
  lifecycle: development
  owner: user:vignesh
  system: Sysco-API-Portal2
  dependsOn:
    - resource:default/payments-db
    - component:default/inventory-service
  providesApis:
    - Sysco-Backend-API3
    - Sysco-Backend-API4
  consumesApis:
    - auth-api
    - auth-api2
