apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: repo2
  description: Repo2 is created by backstage developers.
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: pep8speaks-org/pep8speaks
    datadoghq.com/dashboard-url: https://p.us5.datadoghq.com/sb/accd1c13-63a5-11f0-b32a-4a480b1bb425-0b668ff98e1318bce14e5de894a27ce7
spec:
  type: service
  lifecycle: development
  owner: user:vignesh
  system: repo2-portal
  providesApis:
    - repo2-api
