apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Sysco-Sample-API-Repo2
  description: >
    The Sysco-Sample-API-Repo is designed to provide sample API
    specifications aligned with the Sysco API guidelines.
  annotations:
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: "teamA/artistLookup-build"
    jenkins.io/github-folder: pep8speaks-org/pep8speaks
    datadoghq.com/dashboard-url: https://p.us5.datadoghq.com/sb/accd1c13-63a5-11f0-b32a-4a480b1bb425-0b668ff98e1318bce14e5de894a27ce7
    scorecard/jsonDataUrl: "https://mocki.io/v1/d4867d8b-b5d5-4a48-a4ab-79131b5809b8"
spec:
  type: service
  lifecycle: development
  owner: prodapt
  system: Sysco-API-Portal2
  dependsOn:
    - resource:default/payments-db
    - component:default/inventory-service
  providesApis:
    - Sysco-Backend-API3
    - Sysco-Backend-API4
  consumesApis:
    - auth-api
    - auth-api2
