apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Sysco-Sample-API-Repo2
  description: The Sysco-Sample-API-Repo is designed to provide sample API specifications aligned with the Sysco API guidelines. These specifications are typically offered in the OpenAPI format, ensuring compliance with industry-standard best practices for API design and documentation.
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: pep8speaks-org/pep8speaks
    datadoghq.com/dashboard-url: https://p.us5.datadoghq.com/sb/accd1c13-63a5-11f0-b32a-4a480b1bb425-0b668ff98e1318bce14e5de894a27ce7
spec:
  type: service
  lifecycle: development
  owner: user:vignesh
  system: repo2-portal
  dependsOn:
    - resource:default/payments-db
    - component:default/inventory-service
  providesApis:
    - payments-api
  consumesApis:
    - auth-api
    - auth-api2

