apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inventory-service
  description: Kafka topic for order events
spec:
  type: kafka-topic
  owner: team-ops
  system: commerce-portal
  dependsOn:
    - component:default/order-processor
